#ifndef GIGAACE_VERSION_H
#define GIGAACE_VERSION_H

#define GIGAACE_VERSION_MAJOR 0
#define GIGAACE_VERSION_MINOR 1
#define GIGAACE_VERSION_PATCH 0

#define GIGAACE_VERSION_STR   "0.1.0"
#define GIGAACE_BUILD_DATE    __DATE__
#define GIGAACE_BUILD_TIME    __TIME__

#endif
